### ISSUE TITLE
Adding FCPG via USGS?

### ISSUE THREAD

**Issue by joshualerickson** [mikejohnson51/climateR-catalogs#3]
Hey @mikejohnson51. not sure if this is the right place or how it all comes together but thought of climateR when I was connecting to these .vrt's at `https://prod-is-usgs-sb-prod-publish.s3.amazonaws.com/5f3ab12082ce8df5b6c4076a/params.json` . Have a good one!

**Comment by mikejohnson51** [comment]
Hi @joshualerickson! Sorry for the delay. This is a perfect resource to add. Right now it is not a cataloged element but can still be accessed by URL:

```r

url = 'https://prod-is-usgs-sb-prod-publish.s3.amazonaws.com/5f5155b882ce4c3d12386a0c/lc1_fcpg.vrt'

xx = dap(url, AOI = AOI::aoi_get(state = "OR"))
```


We have an ESIP grant to extend this work. @program--, this is a good, easy dataset to test our auto updating catalog if time allows.

**Comment by mikejohnson51** [comment]
added in non R6 form
