### ISSUE TITLE
Please add MERRA-2

### ISSUE THREAD

**Issue by mikejohnson51** [mikejohnson51/climateR-catalogs#6]
CC @Guo-Badger

# What is the data?

MERRA-2 is the Modern-Era Retrospective analysis for Research and Applications, Version 2

# What is the data format (OpenDap, VRT, TIF)

OpenDap via NASA EarthData

# What is the data URL:

https://disc.gsfc.nasa.gov/datasets?project=MERRA-2

The priority is hourly land surface forcings: https://disc.gsfc.nasa.gov/datasets/M2T1NXLFO_5.12.4/summary

**Comment by Guo-Badger** [comment]
Hi Mike, 

This tag means you are working on it and it is not ready yet. Is it correct?

**Comment by mikejohnson51** [comment]
Correct! We have the data cataloged, just need to merge it here

**Comment by mikejohnson51** [comment]
added in non R6 form

**Comment by Guo-Badger** [comment]
Hi Mike, I am not farmilar with this tool and have no clue what does "added in non R6 form" mean. Will you be able to provide me an example or direct me to the right place?

**Comment by mikejohnson51** [comment]
Yep! Your request came at a tricky time since we are transitioning the entire catalog to a new design. All this means is that I created the merra catalog using the old technique and @program-- will translate it to the R6 method.

Once that’s done we can provide a nice example for you. Typically adding a new product is very easy. The timing was just off this go around.
On Jul 14, 2023 at 2:50 PM -0600, Guo Yu ***@***.***>, wrote:
> Hi Mike, I am not farmilar with this tool and have no clue what does "added in non R6 form" mean. Will you be able to provide me an example or direct me to the right place?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.Message ID: ***@***.***>

-- 
CONFIDENTIALITY NOTICE: This email message, including any attachment(s), is 
intended only for the named recipient(s) and contains confidential, 
proprietary or legally privileged information. Unauthorized individuals or 
entities are not permitted access to this information. Any dissemination, 
distribution, disclosure, or copying of this information is unauthorized 
and strictly prohibited. If you have received this message in error, please 
advise the sender by reply email, and delete this message and any 
attachments.

**Comment by Guo-Badger** [comment]
Got you. I am looking forward to the updated version! I did some research recently and found that OpenDAP is a brillant idea. I notice there is a python package Pydap can also do a similar job.

**Comment by mikejohnson51** [comment]
Yep! It’s a super cool technology! What climateR and climatePy do for you is build, send and structure the queries. It also provides access to other data forms like tifs, vrts, and hdf files on different server types
On Jul 14, 2023 at 3:08 PM -0600, Guo Yu ***@***.***>, wrote:
> Got you. I am looking forward to the updated version! I did some research recently and found that OpenDAP is a brillant idea. I notice there is a python package Pydap can also do a similar job.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.Message ID: ***@***.***>

-- 
CONFIDENTIALITY NOTICE: This email message, including any attachment(s), is 
intended only for the named recipient(s) and contains confidential, 
proprietary or legally privileged information. Unauthorized individuals or 
entities are not permitted access to this information. Any dissemination, 
distribution, disclosure, or copying of this information is unauthorized 
and strictly prohibited. If you have received this message in error, please 
advise the sender by reply email, and delete this message and any 
attachments.

**Comment by Guo-Badger** [comment]
Hi Mike, I wonder do you have any updates on this? Thanks.

**Comment by mikejohnson51** [comment]
Merra2 is in the most recent catalog release. All dap  tools should work! We’ll have a sortcut added soon as well.

Thanks!

Mike Johnson, PhD
Water Resource Data Scientist
Hydrofabric Technical Director, NOAA Office of Water Prediction
www.Lynker.com
Metro DC • Boulder • Honolulu • Tuscaloosa • Seattle • Charleston • Wellington NZ
An Employee-Owned Company
On Aug 2, 2023 at 9:22 AM -0700, Guo Yu ***@***.***>, wrote:
> Hi Mike, I wonder do you have any updates on this? Thanks.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.Message ID: ***@***.***>

-- 
CONFIDENTIALITY NOTICE: This email message, including any attachment(s), is 
intended only for the named recipient(s) and contains confidential, 
proprietary or legally privileged information. Unauthorized individuals or 
entities are not permitted access to this information. Any dissemination, 
distribution, disclosure, or copying of this information is unauthorized 
and strictly prohibited. If you have received this message in error, please 
advise the sender by reply email, and delete this message and any 
attachments.

**Comment by Guo-Badger** [comment]
Sounds great. Is there any tutorial that I can follow to give a try?

**Comment by Guo-Badger** [comment]
Hi Mike, can you send me an example to follow for using this tool? This tool seems new to me. Thanks.
